language: php

php:
  - 5.4

services: mongodb

matrix:
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
  include:
    - php: 5.4
      env:
        - PHPCS=1

before_script: 
  - pecl -q install mongo
  - cp app/config/parameters.yml.test app/config/parameters.yml
  - composer install
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php app/console --env=test doctrine:mongodb:schema:drop
  - php app/console --env=test doctrine:mongodb:schema:create
  - php app/console --env=test doctrine:mongodb:fixtures:load

script: 
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit -c app; else phpcs --extensions=php,js --standard=PSR2 ./src; fi"