parameters:
#    itsallagile_api.example.class: itsallagile\APIBundle\Example

services:
#    itsallagile_api.example:
#        class: %itsallagile_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
