itsallagileScrumboardBundle:
    resource: "@itsallagileScrumboardBundle/Resources/config/routing.yml"
    prefix:   /

WayneCBudgetBundle:
    resource: "@itsallagileCoreBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
