itsallagileAPIBundle:
    resource: "@itsallagileAPIBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
    options: 
        name_prefix: "itsallagileAPIBundle_"

itsallagileScrumboardBundle:
    resource: "@itsallagileScrumboardBundle/Resources/config/routing.yml"
    prefix:   /

itsallagileCoreBundle:
    resource: "@itsallagileCoreBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    pattern:   /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
