homepage:
    pattern:  /home/{name}
    defaults: { _controller: itsallagileCoreBundle:Home:index }
login:
    pattern: /login
    defaults: { _controller: itsallagileCoreBundle:Security:login }
login_check:
    pattern: /login_check
core_register:
    pattern: /register
    defaults: {_controller: itsallagileCoreBundle:Security:register}
core_dashboard:
    pattern: /dashboard
    defaults: { _controller: itsallagileCoreBundle:Dashboard:index }
core_teams:
    pattern: /teams
    defaults: { _controller: itsallagileCoreBundle:Team:index }
core_teams_add:
    pattern: /teams/add
    defaults: { _controller: itsallagileCoreBundle:Team:add }