homepage:
    pattern:  /
    defaults: { _controller: itsallagileCoreBundle:Dashboard:index }
login:
    pattern: /login
    defaults: { _controller: itsallagileCoreBundle:Security:login }
login_check:
    pattern: /login_check
core_register:
    pattern: /register
    defaults: {_controller: itsallagileCoreBundle:Security:register}
core_dashboard:
    pattern: /dashboard
    defaults: { _controller: itsallagileCoreBundle:Dashboard:index }
core_teams:
    pattern: /teams
    defaults: { _controller: itsallagileCoreBundle:Team:index }
core_teams_add:
    pattern: /teams/add
    defaults: { _controller: itsallagileCoreBundle:Team:add }
core_teams_edit:
    pattern: /teams/edit/{id}
    defaults: { _controller: itsallagileCoreBundle:Team:edit }

core_teams_removeUser:
    pattern: /teams/remove-user/team/{id_team}/user/{id_user}
    defaults: { _controller: itsallagileCoreBundle:Team:removeUser }

core_boards_add:
    pattern: /boards/add
    defaults: { _controller: itsallagileCoreBundle:Board:add }