parameters:
#    wayne_c_budget.example.class: itsallagile\CoreBundle\Example

services:
#    wayne_c_budget.example:
#        class: %wayne_c_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
