itsallagileScrumboardBundle_homepage:
    pattern:  /scrumboard
    defaults: { _controller: itsallagileScrumboardBundle:Board:index }

itsallagileScrumboardBundle_taskGet:
    pattern: /ticket/{ticketId}
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:get, _format: json }
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_post:
    pattern: /ticket
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:post, _format: json }
    requirements:
        _method: POST
        format: JSON
