itsallagileScrumboardBundle_viewboard:
    pattern:  /scrumboard/{slug}
    defaults: { _controller: itsallagileScrumboardBundle:Scrumboard:index }

itsallagileScrumboardBundle_ticketsGetBoard:
    pattern: /api/tickets/board/{boardId}
    defaults: { _controller: itsallagileScrumboardBundle:Tickets:getForBoard, _format: json}
    requirements:
        _method: GET
        format: JSON

itsallagileScrumboardBundle_ticketsDelete:
    pattern: /api/tickets/{ticketId}
    defaults: { _controller: itsallagileScrumboardBundle:Tickets:delete, _format: json }
    requirements:
        _method: DELETE
        format: JSON
        
            
itsallagileScrumboardBundle_storiesGetAll:
    pattern: /api/stories
    defaults: { _controller: itsallagileScrumboardBundle:Stories:getAll, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_storiesGetOne:
    pattern: /api/stories/{storyId}
    defaults: { _controller: itsallagileScrumboardBundle:Stories:get, _format: json}
    requirements:
        _method: GET
        format: JSON
        
                
itsallagileScrumboardBundle_storiesGetBoard:
    pattern: /api/stories/board/{boardId}
    defaults: { _controller: itsallagileScrumboardBundle:Stories:getForBoard, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_storiespost:
    pattern: /api/stories
    defaults: { _controller: itsallagileScrumboardBundle:Stories:post, _format: json }
    requirements:
        _method: POST
        format: JSON
        
itsallagileScrumboardBundle_storiesPut:
    pattern: /api/stories/{storyId}
    defaults: { _controller: itsallagileScrumboardBundle:Stories:put, _format: json }
    requirements:
        _method: PUT
        format: JSON
        
itsallagileScrumboardBundle_storiesDelete:
    pattern: /api/stories/{storyId}
    defaults: { _controller: itsallagileScrumboardBundle:Stories:delete, _format: json }
    requirements:
        _method: DELETE
        format: JSON
        
        
itsallagileScrumboardBundle_statusesGetAll:
    pattern: /api/statuses
    defaults: { _controller: itsallagileScrumboardBundle:Statuses:getAll, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_statusesGetOne:
    pattern: /api/statuses/{statusId}
    defaults: { _controller: itsallagileScrumboardBundle:Statuses:get, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_storyStatusesGetAll:
    pattern: /api/storyStatuses
    defaults: { _controller: itsallagileScrumboardBundle:StoryStatuses:getAll, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_storyStatusesGetOne:
    pattern: /api/storyStatuses/{statusId}
    defaults: { _controller: itsallagileScrumboardBundle:StoryStatuses:get, _format: json}
    requirements:
        _method: GET
        format: JSON

itsallagileScrumboardBundle_chatMessagesGetOne:
    pattern: /api/chatMessages/{chatMessageId}
    defaults: { _controller: itsallagileScrumboardBundle:ChatMessages:get, _format: json}
    requirements:
        _method: GET
        format: JSON
        
                
itsallagileScrumboardBundle_chatMessagesGetBoard:
    pattern: /api/chatMessages/board/{boardId}
    defaults: { _controller: itsallagileScrumboardBundle:ChatMessages:getForBoard, _format: json}
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_chatMessagesPost:
    pattern: /api/chatMessages
    defaults: { _controller: itsallagileScrumboardBundle:ChatMessages:post, _format: json }
    requirements:
        _method: POST
        format: JSON