itsallagileScrumboardBundle_homepage:
    pattern:  /scrumboard
    defaults: { _controller: itsallagileScrumboardBundle:Board:index }

itsallagileScrumboardBundle_ticketGet:
    pattern: /ticket/{ticketId}
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:get, _format: json }
    requirements:
        _method: GET
        format: JSON
        
itsallagileScrumboardBundle_ticketpost:
    pattern: /ticket
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:post, _format: json }
    requirements:
        _method: POST
        format: JSON
        
itsallagileScrumboardBundle_ticketPut:
    pattern: /ticket/{ticketId}
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:put, _format: json }
    requirements:
        _method: PUT
        format: JSON
        
itsallagileScrumboardBundle_ticketDelete:
    pattern: /ticket/{ticketId}
    defaults: { _controller: itsallagileScrumboardBundle:Ticket:delete, _format: json }
    requirements:
        _method: DELETE
        format: JSON
        
        
itsallagileScrumboardBundle_ticketsGet:
    pattern: /tickets
    defaults: { _controller: itsallagileScrumboardBundle:Tickets:get, _format: json }
    requirements:
        _method: GET
        format: JSON