parameters:
#    itsallagile_scrumboard.example.class: itsallagile\ScrumboardBundle\Example

services:
#    itsallagile_scrumboard.example:
#        class: %itsallagile_scrumboard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
